/**
 * ICAO/IATA to IATA + city for display. FR24 returns ICAO; we show IATA (city).
 */
export type AirportDisplay = { iata: string; city: string };

const AIRPORTS: Record<string, AirportDisplay> = {
  // Turkey
  LTFJ: { iata: 'SAW', city: 'Istanbul' },
  SAW: { iata: 'SAW', city: 'Istanbul' },
  LTFM: { iata: 'IST', city: 'Istanbul' },
  IST: { iata: 'IST', city: 'Istanbul' },
  LTAI: { iata: 'AYT', city: 'Antalya' },
  AYT: { iata: 'AYT', city: 'Antalya' },
  LTBJ: { iata: 'BJV', city: 'Bodrum' },
  BJV: { iata: 'BJV', city: 'Bodrum' },
  LTBS: { iata: 'DLM', city: 'Dalaman' },
  DLM: { iata: 'DLM', city: 'Dalaman' },
  // LTFB is Selçuk–Efes (İzmir). No standard IATA; keep ICAO for display.
  LTFB: { iata: 'LTFB', city: 'Selçuk (Efes)' },
  ESB: { iata: 'ESB', city: 'Ankara' },
  LTCI: { iata: 'IZM', city: 'Izmir' },
  IZM: { iata: 'IZM', city: 'Izmir' },
  LTAF: { iata: 'ADB', city: 'Izmir' },
  ADB: { iata: 'ADB', city: 'Izmir' },
  LTCG: { iata: 'TZX', city: 'Trabzon' },
  TZX: { iata: 'TZX', city: 'Trabzon' },
  LTAH: { iata: 'ADA', city: 'Adana' },
  ADA: { iata: 'ADA', city: 'Adana' },
  LTFE: { iata: 'BXN', city: 'Bodrum' },
  // LTAC is Ankara Esenboğa.
  LTAC: { iata: 'ESB', city: 'Ankara' },
  // Some APIs use metropolitan/city codes (e.g. ANK). Normalize to main airport for display.
  ANK: { iata: 'ESB', city: 'Ankara' },
  // Pakistan (e.g. OPKC)
  OPKC: { iata: 'KHI', city: 'Karachi' },
  KHI: { iata: 'KHI', city: 'Karachi' },
  OPRN: { iata: 'ISB', city: 'Islamabad' },
  ISB: { iata: 'ISB', city: 'Islamabad' },
  OPLA: { iata: 'LHE', city: 'Lahore' },
  LHE: { iata: 'LHE', city: 'Lahore' },
  // Germany
  EDDF: { iata: 'FRA', city: 'Frankfurt' },
  FRA: { iata: 'FRA', city: 'Frankfurt' },
  EDDM: { iata: 'MUC', city: 'Munich' },
  MUC: { iata: 'MUC', city: 'Munich' },
  EDDL: { iata: 'DUS', city: 'Düsseldorf' },
  DUS: { iata: 'DUS', city: 'Düsseldorf' },
  // UK
  EGLL: { iata: 'LHR', city: 'London' },
  LHR: { iata: 'LHR', city: 'London' },
  EGKK: { iata: 'LGW', city: 'London' },
  LGW: { iata: 'LGW', city: 'London' },
  // Netherlands
  EHAM: { iata: 'AMS', city: 'Amsterdam' },
  AMS: { iata: 'AMS', city: 'Amsterdam' },
  // France
  LFPG: { iata: 'CDG', city: 'Paris' },
  CDG: { iata: 'CDG', city: 'Paris' },
  LFLL: { iata: 'LYS', city: 'Lyon' },
  LYS: { iata: 'LYS', city: 'Lyon' },
  // Spain
  LEMD: { iata: 'MAD', city: 'Madrid' },
  MAD: { iata: 'MAD', city: 'Madrid' },
  LEBL: { iata: 'BCN', city: 'Barcelona' },
  BCN: { iata: 'BCN', city: 'Barcelona' },
  // Austria
  LOWW: { iata: 'VIE', city: 'Vienna' },
  VIE: { iata: 'VIE', city: 'Vienna' },
  // Switzerland
  LSZH: { iata: 'ZRH', city: 'Zurich' },
  ZRH: { iata: 'ZRH', city: 'Zurich' },
  // UAE
  OMDB: { iata: 'DXB', city: 'Dubai' },
  DXB: { iata: 'DXB', city: 'Dubai' },
  OMSJ: { iata: 'SHJ', city: 'Sharjah' },
  SHJ: { iata: 'SHJ', city: 'Sharjah' },
  // Qatar
  OTBD: { iata: 'DOH', city: 'Doha' },
  OTHH: { iata: 'DOH', city: 'Doha' },
  DOH: { iata: 'DOH', city: 'Doha' },
  // Russia
  UUEE: { iata: 'SVO', city: 'Moscow' },
  SVO: { iata: 'SVO', city: 'Moscow' },
  // Cyprus
  LCLK: { iata: 'LCA', city: 'Larnaca' },
  LCA: { iata: 'LCA', city: 'Larnaca' },
  LCRA: { iata: 'PFO', city: 'Paphos' },
  PFO: { iata: 'PFO', city: 'Paphos' },
  // More Gulf / Middle East
  OBBI: { iata: 'BAH', city: 'Bahrain' },
  BAH: { iata: 'BAH', city: 'Bahrain' },
  OKBK: { iata: 'KWI', city: 'Kuwait City' },
  KWI: { iata: 'KWI', city: 'Kuwait City' },
  OOMS: { iata: 'MCT', city: 'Muscat' },
  MCT: { iata: 'MCT', city: 'Muscat' },
  OERK: { iata: 'RUH', city: 'Riyadh' },
  RUH: { iata: 'RUH', city: 'Riyadh' },
  OEJN: { iata: 'JED', city: 'Jeddah' },
  JED: { iata: 'JED', city: 'Jeddah' },
  OEDR: { iata: 'DMM', city: 'Dammam' },
  DMM: { iata: 'DMM', city: 'Dammam' },
  OIIE: { iata: 'IKA', city: 'Tehran' },
  IKA: { iata: 'IKA', city: 'Tehran' },
  OTBH: { iata: 'DOH', city: 'Doha' },
  // Greece
  LGAV: { iata: 'ATH', city: 'Athens' },
  ATH: { iata: 'ATH', city: 'Athens' },
  LGRP: { iata: 'RHO', city: 'Rhodes' },
  RHO: { iata: 'RHO', city: 'Rhodes' },
  LGSA: { iata: 'CHQ', city: 'Chania' },
  CHQ: { iata: 'CHQ', city: 'Chania' },
  LGIR: { iata: 'HER', city: 'Heraklion' },
  HER: { iata: 'HER', city: 'Heraklion' },
  // Italy
  LIRF: { iata: 'FCO', city: 'Rome' },
  FCO: { iata: 'FCO', city: 'Rome' },
  LIML: { iata: 'MXP', city: 'Milan' },
  MXP: { iata: 'MXP', city: 'Milan' },
  LIPZ: { iata: 'VCE', city: 'Venice' },
  VCE: { iata: 'VCE', city: 'Venice' },
  LIME: { iata: 'BGY', city: 'Milan' },
  BGY: { iata: 'BGY', city: 'Milan' },
  // Portugal
  LPPT: { iata: 'LIS', city: 'Lisbon' },
  LIS: { iata: 'LIS', city: 'Lisbon' },
  LPPR: { iata: 'OPO', city: 'Porto' },
  OPO: { iata: 'OPO', city: 'Porto' },
  // Belgium, Ireland
  EBBR: { iata: 'BRU', city: 'Brussels' },
  BRU: { iata: 'BRU', city: 'Brussels' },
  EIDW: { iata: 'DUB', city: 'Dublin' },
  DUB: { iata: 'DUB', city: 'Dublin' },
  // USA (major hubs)
  KJFK: { iata: 'JFK', city: 'New York' },
  JFK: { iata: 'JFK', city: 'New York' },
  KORD: { iata: 'ORD', city: 'Chicago' },
  ORD: { iata: 'ORD', city: 'Chicago' },
  KLAX: { iata: 'LAX', city: 'Los Angeles' },
  LAX: { iata: 'LAX', city: 'Los Angeles' },
  KEWR: { iata: 'EWR', city: 'Newark' },
  EWR: { iata: 'EWR', city: 'Newark' },
  KMIA: { iata: 'MIA', city: 'Miami' },
  MIA: { iata: 'MIA', city: 'Miami' },
  KATL: { iata: 'ATL', city: 'Atlanta' },
  ATL: { iata: 'ATL', city: 'Atlanta' },
  KDFW: { iata: 'DFW', city: 'Dallas' },
  DFW: { iata: 'DFW', city: 'Dallas' },
  KDEN: { iata: 'DEN', city: 'Denver' },
  DEN: { iata: 'DEN', city: 'Denver' },
  KSFO: { iata: 'SFO', city: 'San Francisco' },
  SFO: { iata: 'SFO', city: 'San Francisco' },
  KIAD: { iata: 'IAD', city: 'Washington' },
  IAD: { iata: 'IAD', city: 'Washington' },
  KBOS: { iata: 'BOS', city: 'Boston' },
  BOS: { iata: 'BOS', city: 'Boston' },
  KSEA: { iata: 'SEA', city: 'Seattle' },
  SEA: { iata: 'SEA', city: 'Seattle' },
  // Canada
  CYYZ: { iata: 'YYZ', city: 'Toronto' },
  YYZ: { iata: 'YYZ', city: 'Toronto' },
  CYVR: { iata: 'YVR', city: 'Vancouver' },
  YVR: { iata: 'YVR', city: 'Vancouver' },
  CYYC: { iata: 'YYC', city: 'Calgary' },
  YYC: { iata: 'YYC', city: 'Calgary' },
  // Asia
  VHHH: { iata: 'HKG', city: 'Hong Kong' },
  HKG: { iata: 'HKG', city: 'Hong Kong' },
  WSSS: { iata: 'SIN', city: 'Singapore' },
  SIN: { iata: 'SIN', city: 'Singapore' },
  VTBS: { iata: 'BKK', city: 'Bangkok' },
  BKK: { iata: 'BKK', city: 'Bangkok' },
  RJAA: { iata: 'NRT', city: 'Tokyo' },
  NRT: { iata: 'NRT', city: 'Tokyo' },
  RJTT: { iata: 'HND', city: 'Tokyo' },
  HND: { iata: 'HND', city: 'Tokyo' },
  ZSPD: { iata: 'PVG', city: 'Shanghai' },
  PVG: { iata: 'PVG', city: 'Shanghai' },
  VIDP: { iata: 'DEL', city: 'Delhi' },
  DEL: { iata: 'DEL', city: 'Delhi' },
  VABB: { iata: 'BOM', city: 'Mumbai' },
  BOM: { iata: 'BOM', city: 'Mumbai' },
  // Pegasus Airlines destinations
  LATI: { iata: 'TIA', city: 'Tirana' },
  TIA: { iata: 'TIA', city: 'Tirana' },
  DAAG: { iata: 'ALG', city: 'Algiers' },
  ALG: { iata: 'ALG', city: 'Algiers' },
  UDYZ: { iata: 'EVN', city: 'Yerevan' },
  EVN: { iata: 'EVN', city: 'Yerevan' },
  UBBB: { iata: 'GYD', city: 'Baku' },
  GYD: { iata: 'GYD', city: 'Baku' },
  UBBG: { iata: 'KVD', city: 'Ganja' },
  KVD: { iata: 'KVD', city: 'Ganja' },
  EBCI: { iata: 'CRL', city: 'Charleroi' },
  CRL: { iata: 'CRL', city: 'Charleroi' },
  LQSA: { iata: 'SJJ', city: 'Sarajevo' },
  SJJ: { iata: 'SJJ', city: 'Sarajevo' },
  LQTZ: { iata: 'TZL', city: 'Tuzla' },
  TZL: { iata: 'TZL', city: 'Tuzla' },
  LBPD: { iata: 'PDV', city: 'Plovdiv' },
  PDV: { iata: 'PDV', city: 'Plovdiv' },
  LBSF: { iata: 'SOF', city: 'Sofia' },
  SOF: { iata: 'SOF', city: 'Sofia' },
  LDZA: { iata: 'ZAG', city: 'Zagreb' },
  ZAG: { iata: 'ZAG', city: 'Zagreb' },
  LCEN: { iata: 'ECN', city: 'Ercan' },
  ECN: { iata: 'ECN', city: 'Ercan' },
  LKPR: { iata: 'PRG', city: 'Prague' },
  PRG: { iata: 'PRG', city: 'Prague' },
  EKCH: { iata: 'CPH', city: 'Copenhagen' },
  CPH: { iata: 'CPH', city: 'Copenhagen' },
  HEAX: { iata: 'SPX', city: 'Cairo' },
  SPX: { iata: 'SPX', city: 'Cairo' },
  HEGN: { iata: 'HRG', city: 'Hurghada' },
  HRG: { iata: 'HRG', city: 'Hurghada' },
  HESH: { iata: 'SSH', city: 'Sharm El Sheikh' },
  SSH: { iata: 'SSH', city: 'Sharm El Sheikh' },
  EFHK: { iata: 'HEL', city: 'Helsinki' },
  HEL: { iata: 'HEL', city: 'Helsinki' },
  LFML: { iata: 'MRS', city: 'Marseille' },
  MRS: { iata: 'MRS', city: 'Marseille' },
  LFPO: { iata: 'ORY', city: 'Paris' },
  ORY: { iata: 'ORY', city: 'Paris' },
  LFMH: { iata: 'EBU', city: 'Saint-Étienne' },
  EBU: { iata: 'EBU', city: 'Saint-Étienne' },
  EDDB: { iata: 'BER', city: 'Berlin' },
  BER: { iata: 'BER', city: 'Berlin' },
  EDDW: { iata: 'BRE', city: 'Bremen' },
  BRE: { iata: 'BRE', city: 'Bremen' },
  EDDK: { iata: 'CGN', city: 'Cologne' },
  CGN: { iata: 'CGN', city: 'Cologne' },
  EDLW: { iata: 'DTM', city: 'Dortmund' },
  DTM: { iata: 'DTM', city: 'Dortmund' },
  EDDE: { iata: 'ERF', city: 'Erfurt' },
  ERF: { iata: 'ERF', city: 'Erfurt' },
  EDDH: { iata: 'HAM', city: 'Hamburg' },
  HAM: { iata: 'HAM', city: 'Hamburg' },
  EDDV: { iata: 'HAJ', city: 'Hanover' },
  HAJ: { iata: 'HAJ', city: 'Hanover' },
  EDDP: { iata: 'LEJ', city: 'Leipzig' },
  LEJ: { iata: 'LEJ', city: 'Leipzig' },
  EDDN: { iata: 'NUE', city: 'Nuremberg' },
  NUE: { iata: 'NUE', city: 'Nuremberg' },
  EDDS: { iata: 'STR', city: 'Stuttgart' },
  STR: { iata: 'STR', city: 'Stuttgart' },
  UGSB: { iata: 'BUS', city: 'Batumi' },
  BUS: { iata: 'BUS', city: 'Batumi' },
  UGKO: { iata: 'KUT', city: 'Kutaisi' },
  KUT: { iata: 'KUT', city: 'Kutaisi' },
  UGTB: { iata: 'TBS', city: 'Tbilisi' },
  TBS: { iata: 'TBS', city: 'Tbilisi' },
  LHBP: { iata: 'BUD', city: 'Budapest' },
  BUD: { iata: 'BUD', city: 'Budapest' },
  OITT: { iata: 'TBZ', city: 'Tabriz' },
  TBZ: { iata: 'TBZ', city: 'Tabriz' },
  ORBI: { iata: 'BGW', city: 'Baghdad' },
  BGW: { iata: 'BGW', city: 'Baghdad' },
  ORMM: { iata: 'BSR', city: 'Basra' },
  BSR: { iata: 'BSR', city: 'Basra' },
  ORER: { iata: 'EBL', city: 'Erbil' },
  EBL: { iata: 'EBL', city: 'Erbil' },
  LLBG: { iata: 'TLV', city: 'Tel Aviv' },
  TLV: { iata: 'TLV', city: 'Tel Aviv' },
  LIPE: { iata: 'BLQ', city: 'Bologna' },
  BLQ: { iata: 'BLQ', city: 'Bologna' },
  OJAM: { iata: 'AMM', city: 'Amman' },
  AMM: { iata: 'AMM', city: 'Amman' },
  UAAA: { iata: 'ALA', city: 'Almaty' },
  ALA: { iata: 'ALA', city: 'Almaty' },
  UATE: { iata: 'SCO', city: 'Aqtau' },
  SCO: { iata: 'SCO', city: 'Aqtau' },
  UATT: { iata: 'AKX', city: 'Aqtöbe' },
  AKX: { iata: 'AKX', city: 'Aqtöbe' },
  UACC: { iata: 'NQZ', city: 'Astana' },
  NQZ: { iata: 'NQZ', city: 'Astana' },
  UATG: { iata: 'GUW', city: 'Atyrau' },
  GUW: { iata: 'GUW', city: 'Atyrau' },
  UAII: { iata: 'CIT', city: 'Shymkent' },
  CIT: { iata: 'CIT', city: 'Shymkent' },
  BKPR: { iata: 'PRN', city: 'Pristina' },
  PRN: { iata: 'PRN', city: 'Pristina' },
  UAFM: { iata: 'FRU', city: 'Bishkek' },
  FRU: { iata: 'FRU', city: 'Bishkek' },
  UAFO: { iata: 'OSS', city: 'Osh' },
  OSS: { iata: 'OSS', city: 'Osh' },
  OLBA: { iata: 'BEY', city: 'Beirut' },
  BEY: { iata: 'BEY', city: 'Beirut' },
  LUKK: { iata: 'KIV', city: 'Chișinău' },
  KIV: { iata: 'KIV', city: 'Chișinău' },
  GMMN: { iata: 'CMN', city: 'Casablanca' },
  CMN: { iata: 'CMN', city: 'Casablanca' },
  EHEH: { iata: 'EIN', city: 'Eindhoven' },
  EIN: { iata: 'EIN', city: 'Eindhoven' },
  EHRD: { iata: 'RTM', city: 'Rotterdam' },
  RTM: { iata: 'RTM', city: 'Rotterdam' },
  LWSK: { iata: 'SKP', city: 'Skopje' },
  SKP: { iata: 'SKP', city: 'Skopje' },
  ENGM: { iata: 'OSL', city: 'Oslo' },
  OSL: { iata: 'OSL', city: 'Oslo' },
  EPKK: { iata: 'KRK', city: 'Krakow' },
  KRK: { iata: 'KRK', city: 'Krakow' },
  EPWA: { iata: 'WAW', city: 'Warsaw' },
  WAW: { iata: 'WAW', city: 'Warsaw' },
  LROP: { iata: 'OTP', city: 'Bucharest' },
  OTP: { iata: 'OTP', city: 'Bucharest' },
  UUDD: { iata: 'DME', city: 'Moscow' },
  DME: { iata: 'DME', city: 'Moscow' },
  ULLI: { iata: 'LED', city: 'Saint Petersburg' },
  LED: { iata: 'LED', city: 'Saint Petersburg' },
  URMM: { iata: 'MRV', city: 'Mineralnye Vody' },
  MRV: { iata: 'MRV', city: 'Mineralnye Vody' },
  URMG: { iata: 'GRV', city: 'Grozny' },
  GRV: { iata: 'GRV', city: 'Grozny' },
  OEMA: { iata: 'MED', city: 'Medina' },
  MED: { iata: 'MED', city: 'Medina' },
  LEZL: { iata: 'SVQ', city: 'Seville' },
  SVQ: { iata: 'SVQ', city: 'Seville' },
  LYBE: { iata: 'BEG', city: 'Belgrade' },
  BEG: { iata: 'BEG', city: 'Belgrade' },
  LZIB: { iata: 'BTS', city: 'Bratislava' },
  BTS: { iata: 'BTS', city: 'Bratislava' },
  ESSA: { iata: 'ARN', city: 'Stockholm' },
  ARN: { iata: 'ARN', city: 'Stockholm' },
  LSGG: { iata: 'GVA', city: 'Geneva' },
  GVA: { iata: 'GVA', city: 'Geneva' },
  LFSB: { iata: 'BSL', city: 'Basel' },
  BSL: { iata: 'BSL', city: 'Basel' },
  EGBB: { iata: 'BHX', city: 'Birmingham' },
  BHX: { iata: 'BHX', city: 'Birmingham' },
  EGGD: { iata: 'BRS', city: 'Bristol' },
  BRS: { iata: 'BRS', city: 'Bristol' },
  EGSS: { iata: 'STN', city: 'London' },
  STN: { iata: 'STN', city: 'London' },
  EGCC: { iata: 'MAN', city: 'Manchester' },
  MAN: { iata: 'MAN', city: 'Manchester' },
  EGPH: { iata: 'EDI', city: 'Edinburgh' },
  EDI: { iata: 'EDI', city: 'Edinburgh' },
  OMAA: { iata: 'AUH', city: 'Abu Dhabi' },
  AUH: { iata: 'AUH', city: 'Abu Dhabi' },
  LTGP: { iata: 'GZP', city: 'Gazipaşa' },
  GZP: { iata: 'GZP', city: 'Gazipaşa' },
  LTAP: { iata: 'MZH', city: 'Amasya' },
  MZH: { iata: 'MZH', city: 'Amasya' },
  LTCJ: { iata: 'BAL', city: 'Batman' },
  BAL: { iata: 'BAL', city: 'Batman' },
  LTCU: { iata: 'BGG', city: 'Bingöl' },
  BGG: { iata: 'BGG', city: 'Bingöl' },
  LTFD: { iata: 'EDO', city: 'Edremit' },
  EDO: { iata: 'EDO', city: 'Edremit' },
  LTAY: { iata: 'DNZ', city: 'Denizli' },
  DNZ: { iata: 'DNZ', city: 'Denizli' },
  LTCC: { iata: 'DIY', city: 'Diyarbakır' },
  DIY: { iata: 'DIY', city: 'Diyarbakır' },
  LTCA: { iata: 'EZS', city: 'Elazığ' },
  EZS: { iata: 'EZS', city: 'Elazığ' },
  LTCD: { iata: 'ERC', city: 'Erzincan' },
  ERC: { iata: 'ERC', city: 'Erzincan' },
  LTCE: { iata: 'ERZ', city: 'Erzurum' },
  ERZ: { iata: 'ERZ', city: 'Erzurum' },
  LTAJ: { iata: 'GZT', city: 'Gaziantep' },
  GZT: { iata: 'GZT', city: 'Gaziantep' },
  LTCT: { iata: 'IGD', city: 'Iğdır' },
  IGD: { iata: 'IGD', city: 'Iğdır' },
  LTCN: { iata: 'KCM', city: 'Kahramanmaraş' },
  KCM: { iata: 'KCM', city: 'Kahramanmaraş' },
  LTCF: { iata: 'KSY', city: 'Kars' },
  KSY: { iata: 'KSY', city: 'Kars' },
  LTAU: { iata: 'ASR', city: 'Kayseri' },
  ASR: { iata: 'ASR', city: 'Kayseri' },
  LTAN: { iata: 'KYA', city: 'Konya' },
  KYA: { iata: 'KYA', city: 'Konya' },
  LTBZ: { iata: 'KZR', city: 'Kütahya' },
  KZR: { iata: 'KZR', city: 'Kütahya' },
  LTAT: { iata: 'MLX', city: 'Malatya' },
  MLX: { iata: 'MLX', city: 'Malatya' },
  LTCR: { iata: 'MQM', city: 'Mardin' },
  MQM: { iata: 'MQM', city: 'Mardin' },
  LTCK: { iata: 'MSR', city: 'Muş' },
  MSR: { iata: 'MSR', city: 'Muş' },
  LTCB: { iata: 'OGU', city: 'Ordu' },
  OGU: { iata: 'OGU', city: 'Ordu' },
  LTFU: { iata: 'RZV', city: 'Rize' },
  RZV: { iata: 'RZV', city: 'Rize' },
  LFHN: { iata: 'SZF', city: 'Samsun' },
  SZF: { iata: 'SZF', city: 'Samsun' },
  LTCS: { iata: 'GNY', city: 'Şanlıurfa' },
  GNY: { iata: 'GNY', city: 'Şanlıurfa' },
  LTCP: { iata: 'SIC', city: 'Sinop' },
  SIC: { iata: 'SIC', city: 'Sinop' },
  LTAR: { iata: 'VAS', city: 'Sivas' },
  VAS: { iata: 'VAS', city: 'Sivas' },
  LTFC: { iata: 'TEQ', city: 'Tekirdağ' },
  TEQ: { iata: 'TEQ', city: 'Tekirdağ' },
  LTCI: { iata: 'VAN', city: 'Van' },
  VAN: { iata: 'VAN', city: 'Van' },
};

export function getAirportDisplay(code: string | null | undefined): { iata: string; city: string } | null {
  if (!code || typeof code !== 'string') return null;
  const key = code.trim().toUpperCase();
  return AIRPORTS[key] ?? null;
}

/** Format for list: "IATA (City)" or "CODE" if unknown. Pass cityFromDb to prefer stored city. */
export function formatAirportForList(
  code: string | null | undefined,
  cityFromDb?: string | null
): string {
  if (!code || !code.trim()) return '—';
  const info = getAirportDisplay(code);
  const city = (cityFromDb && cityFromDb.trim()) || info?.city;
  if (info) return city ? `${info.iata} (${city})` : info.iata;
  return cityFromDb?.trim() ? `${code.trim()} (${cityFromDb.trim()})` : code.trim();
}

/** Format for flight list: "City (CODE)" e.g. "Doha (DOH)". Prefer cityFromDb when provided. */
export function formatCityAndCode(
  code: string | null | undefined,
  cityFromDb?: string | null
): string {
  if (!code || !code.trim()) return '—';
  const info = getAirportDisplay(code);
  const city = (cityFromDb && cityFromDb.trim()) || info?.city;
  const codeDisplay = info?.iata ?? code.trim();
  if (city) return `${city} (${codeDisplay})`;
  return codeDisplay;
}

/** IANA timezone for airport (code = ICAO or IATA). Used to show local (L) times. */
const AIRPORT_TIMEZONES: Record<string, string> = {
  LTFJ: 'Europe/Istanbul', SAW: 'Europe/Istanbul', LTFM: 'Europe/Istanbul', IST: 'Europe/Istanbul',
  LTAI: 'Europe/Istanbul', AYT: 'Europe/Istanbul', LTBJ: 'Europe/Istanbul', BJV: 'Europe/Istanbul',
  LTBS: 'Europe/Istanbul', DLM: 'Europe/Istanbul', LTFB: 'Europe/Istanbul', ESB: 'Europe/Istanbul',
  LTCI: 'Europe/Istanbul', IZM: 'Europe/Istanbul', LTAF: 'Europe/Istanbul', ADB: 'Europe/Istanbul',
  LTCG: 'Europe/Istanbul', TZX: 'Europe/Istanbul', LTAH: 'Europe/Istanbul', ADA: 'Europe/Istanbul',
  LTFE: 'Europe/Istanbul', LTAC: 'Europe/Istanbul', ANK: 'Europe/Istanbul',
  OPKC: 'Asia/Karachi', KHI: 'Asia/Karachi', OPRN: 'Asia/Karachi', ISB: 'Asia/Karachi',
  OPLA: 'Asia/Karachi', LHE: 'Asia/Karachi',
  EDDF: 'Europe/Berlin', FRA: 'Europe/Berlin', EDDM: 'Europe/Berlin', MUC: 'Europe/Berlin',
  EDDL: 'Europe/Berlin', DUS: 'Europe/Berlin',
  EGLL: 'Europe/London', LHR: 'Europe/London', EGKK: 'Europe/London', LGW: 'Europe/London',
  EHAM: 'Europe/Amsterdam', AMS: 'Europe/Amsterdam',
  LFPG: 'Europe/Paris', CDG: 'Europe/Paris', LFLL: 'Europe/Paris', LYS: 'Europe/Paris',
  LEMD: 'Europe/Madrid', MAD: 'Europe/Madrid', LEBL: 'Europe/Madrid', BCN: 'Europe/Madrid',
  LOWW: 'Europe/Vienna', VIE: 'Europe/Vienna',
  LSZH: 'Europe/Zurich', ZRH: 'Europe/Zurich',
  OMDB: 'Asia/Dubai', DXB: 'Asia/Dubai', OMSJ: 'Asia/Dubai', SHJ: 'Asia/Dubai',
  OTBD: 'Asia/Qatar', OTHH: 'Asia/Qatar', DOH: 'Asia/Qatar',
  UUEE: 'Europe/Moscow', SVO: 'Europe/Moscow',
  LCLK: 'Asia/Nicosia', LCA: 'Asia/Nicosia', LCRA: 'Asia/Nicosia', PFO: 'Asia/Nicosia',
  OBBI: 'Asia/Bahrain', BAH: 'Asia/Bahrain',
  OKBK: 'Asia/Kuwait', KWI: 'Asia/Kuwait',
  OOMS: 'Asia/Muscat', MCT: 'Asia/Muscat',
  OERK: 'Asia/Riyadh', RUH: 'Asia/Riyadh', OEJN: 'Asia/Riyadh', JED: 'Asia/Riyadh', OEDR: 'Asia/Riyadh', DMM: 'Asia/Riyadh',
  OIIE: 'Asia/Tehran', IKA: 'Asia/Tehran', OTBH: 'Asia/Qatar',
  LGAV: 'Europe/Athens', ATH: 'Europe/Athens', LGRP: 'Europe/Athens', RHO: 'Europe/Athens', LGSA: 'Europe/Athens', CHQ: 'Europe/Athens', LGIR: 'Europe/Athens', HER: 'Europe/Athens',
  LIRF: 'Europe/Rome', FCO: 'Europe/Rome', LIML: 'Europe/Rome', MXP: 'Europe/Rome', LIPZ: 'Europe/Rome', VCE: 'Europe/Rome', LIME: 'Europe/Rome', BGY: 'Europe/Rome',
  LPPT: 'Europe/Lisbon', LIS: 'Europe/Lisbon', LPPR: 'Europe/Lisbon', OPO: 'Europe/Lisbon',
  EBBR: 'Europe/Brussels', BRU: 'Europe/Brussels', EIDW: 'Europe/Dublin', DUB: 'Europe/Dublin',
  KJFK: 'America/New_York', JFK: 'America/New_York', KEWR: 'America/New_York', EWR: 'America/New_York', KIAD: 'America/New_York', IAD: 'America/New_York', KBOS: 'America/New_York', BOS: 'America/New_York',
  KORD: 'America/Chicago', ORD: 'America/Chicago', KDFW: 'America/Chicago', DFW: 'America/Chicago',
  KLAX: 'America/Los_Angeles', LAX: 'America/Los_Angeles', KSFO: 'America/Los_Angeles', SFO: 'America/Los_Angeles', KSEA: 'America/Los_Angeles', SEA: 'America/Los_Angeles',
  KMIA: 'America/New_York', MIA: 'America/New_York', KATL: 'America/New_York', ATL: 'America/New_York', KDEN: 'America/Denver', DEN: 'America/Denver',
  CYYZ: 'America/Toronto', YYZ: 'America/Toronto', CYVR: 'America/Vancouver', YVR: 'America/Vancouver', CYYC: 'America/Edmonton', YYC: 'America/Edmonton',
  VHHH: 'Asia/Hong_Kong', HKG: 'Asia/Hong_Kong',
  WSSS: 'Asia/Singapore', SIN: 'Asia/Singapore',
  VTBS: 'Asia/Bangkok', BKK: 'Asia/Bangkok',
  RJAA: 'Asia/Tokyo', NRT: 'Asia/Tokyo', RJTT: 'Asia/Tokyo', HND: 'Asia/Tokyo',
  ZSPD: 'Asia/Shanghai', PVG: 'Asia/Shanghai',
  VIDP: 'Asia/Kolkata', DEL: 'Asia/Kolkata', VABB: 'Asia/Kolkata', BOM: 'Asia/Kolkata',
  // Pegasus Airlines destinations (all)
  LATI: 'Europe/Tirane', TIA: 'Europe/Tirane',
  DAAG: 'Africa/Algiers', ALG: 'Africa/Algiers',
  UDYZ: 'Asia/Yerevan', EVN: 'Asia/Yerevan',
  UBBB: 'Asia/Baku', GYD: 'Asia/Baku', UBBG: 'Asia/Baku', KVD: 'Asia/Baku',
  EBCI: 'Europe/Brussels', CRL: 'Europe/Brussels',
  LQSA: 'Europe/Sarajevo', SJJ: 'Europe/Sarajevo', LQTZ: 'Europe/Sarajevo', TZL: 'Europe/Sarajevo',
  LBPD: 'Europe/Sofia', PDV: 'Europe/Sofia', LBSF: 'Europe/Sofia', SOF: 'Europe/Sofia',
  LDZA: 'Europe/Zagreb', ZAG: 'Europe/Zagreb',
  LCEN: 'Asia/Nicosia', ECN: 'Asia/Nicosia',
  LKPR: 'Europe/Prague', PRG: 'Europe/Prague',
  EKCH: 'Europe/Copenhagen', CPH: 'Europe/Copenhagen',
  HEAX: 'Africa/Cairo', SPX: 'Africa/Cairo', HEGN: 'Africa/Cairo', HRG: 'Africa/Cairo', HESH: 'Africa/Cairo', SSH: 'Africa/Cairo',
  EFHK: 'Europe/Helsinki', HEL: 'Europe/Helsinki',
  LFML: 'Europe/Paris', MRS: 'Europe/Paris', LFPO: 'Europe/Paris', ORY: 'Europe/Paris', LFMH: 'Europe/Paris', EBU: 'Europe/Paris',
  EDDB: 'Europe/Berlin', BER: 'Europe/Berlin', EDDW: 'Europe/Berlin', BRE: 'Europe/Berlin', EDDK: 'Europe/Berlin', CGN: 'Europe/Berlin',
  EDLW: 'Europe/Berlin', DTM: 'Europe/Berlin', EDDE: 'Europe/Berlin', ERF: 'Europe/Berlin', EDDH: 'Europe/Berlin', HAM: 'Europe/Berlin',
  EDDV: 'Europe/Berlin', HAJ: 'Europe/Berlin', EDDP: 'Europe/Berlin', LEJ: 'Europe/Berlin', EDDN: 'Europe/Berlin', NUE: 'Europe/Berlin', EDDS: 'Europe/Berlin', STR: 'Europe/Berlin',
  UGSB: 'Asia/Tbilisi', BUS: 'Asia/Tbilisi', UGKO: 'Asia/Tbilisi', KUT: 'Asia/Tbilisi', UGTB: 'Asia/Tbilisi', TBS: 'Asia/Tbilisi',
  LHBP: 'Europe/Budapest', BUD: 'Europe/Budapest',
  OITT: 'Asia/Tehran', TBZ: 'Asia/Tehran',
  ORBI: 'Asia/Baghdad', BGW: 'Asia/Baghdad', ORMM: 'Asia/Baghdad', BSR: 'Asia/Baghdad', ORER: 'Asia/Baghdad', EBL: 'Asia/Baghdad',
  LLBG: 'Asia/Jerusalem', TLV: 'Asia/Jerusalem',
  LIPE: 'Europe/Rome', BLQ: 'Europe/Rome',
  OJAM: 'Asia/Amman', AMM: 'Asia/Amman',
  UAAA: 'Asia/Almaty', ALA: 'Asia/Almaty', UATE: 'Asia/Aqtau', SCO: 'Asia/Aqtau', UATT: 'Asia/Aqtobe', AKX: 'Asia/Aqtobe',
  UACC: 'Asia/Almaty', NQZ: 'Asia/Almaty', UATG: 'Asia/Atyrau', GUW: 'Asia/Atyrau', UAII: 'Asia/Almaty', CIT: 'Asia/Almaty',
  BKPR: 'Europe/Belgrade', PRN: 'Europe/Belgrade',
  UAFM: 'Asia/Bishkek', FRU: 'Asia/Bishkek', UAFO: 'Asia/Bishkek', OSS: 'Asia/Bishkek',
  OLBA: 'Asia/Beirut', BEY: 'Asia/Beirut',
  LUKK: 'Europe/Chisinau', KIV: 'Europe/Chisinau',
  GMMN: 'Africa/Casablanca', CMN: 'Africa/Casablanca',
  EHEH: 'Europe/Amsterdam', EIN: 'Europe/Amsterdam', EHRD: 'Europe/Amsterdam', RTM: 'Europe/Amsterdam',
  LWSK: 'Europe/Skopje', SKP: 'Europe/Skopje',
  ENGM: 'Europe/Oslo', OSL: 'Europe/Oslo',
  EPKK: 'Europe/Warsaw', KRK: 'Europe/Warsaw', EPWA: 'Europe/Warsaw', WAW: 'Europe/Warsaw',
  LROP: 'Europe/Bucharest', OTP: 'Europe/Bucharest',
  UUDD: 'Europe/Moscow', DME: 'Europe/Moscow', ULLI: 'Europe/Moscow', LED: 'Europe/Moscow', URMM: 'Europe/Moscow', MRV: 'Europe/Moscow', URMG: 'Europe/Moscow', GRV: 'Europe/Moscow',
  OEMA: 'Asia/Riyadh', MED: 'Asia/Riyadh',
  LEZL: 'Europe/Madrid', SVQ: 'Europe/Madrid',
  LYBE: 'Europe/Belgrade', BEG: 'Europe/Belgrade',
  LZIB: 'Europe/Bratislava', BTS: 'Europe/Bratislava',
  ESSA: 'Europe/Stockholm', ARN: 'Europe/Stockholm',
  LSGG: 'Europe/Zurich', GVA: 'Europe/Zurich', LFSB: 'Europe/Zurich', BSL: 'Europe/Zurich',
  EGBB: 'Europe/London', BHX: 'Europe/London', EGGD: 'Europe/London', BRS: 'Europe/London', EGSS: 'Europe/London', STN: 'Europe/London', EGCC: 'Europe/London', MAN: 'Europe/London', EGPH: 'Europe/London', EDI: 'Europe/London',
  OMAA: 'Asia/Dubai', AUH: 'Asia/Dubai',
  LTGP: 'Europe/Istanbul', GZP: 'Europe/Istanbul', LTAP: 'Europe/Istanbul', MZH: 'Europe/Istanbul', LTCJ: 'Europe/Istanbul', BAL: 'Europe/Istanbul',
  LTCU: 'Europe/Istanbul', BGG: 'Europe/Istanbul', LTFD: 'Europe/Istanbul', EDO: 'Europe/Istanbul', LTAY: 'Europe/Istanbul', DNZ: 'Europe/Istanbul',
  LTCC: 'Europe/Istanbul', DIY: 'Europe/Istanbul', LTCA: 'Europe/Istanbul', EZS: 'Europe/Istanbul', LTCD: 'Europe/Istanbul', ERC: 'Europe/Istanbul', LTCE: 'Europe/Istanbul', ERZ: 'Europe/Istanbul',
  LTAJ: 'Europe/Istanbul', GZT: 'Europe/Istanbul', LTCT: 'Europe/Istanbul', IGD: 'Europe/Istanbul', LTCN: 'Europe/Istanbul', KCM: 'Europe/Istanbul', LTCF: 'Europe/Istanbul', KSY: 'Europe/Istanbul',
  LTAU: 'Europe/Istanbul', ASR: 'Europe/Istanbul', LTAN: 'Europe/Istanbul', KYA: 'Europe/Istanbul', LTBZ: 'Europe/Istanbul', KZR: 'Europe/Istanbul',
  LTAT: 'Europe/Istanbul', MLX: 'Europe/Istanbul', LTCR: 'Europe/Istanbul', MQM: 'Europe/Istanbul', LTCK: 'Europe/Istanbul', MSR: 'Europe/Istanbul',
  LTCB: 'Europe/Istanbul', OGU: 'Europe/Istanbul', LTFU: 'Europe/Istanbul', RZV: 'Europe/Istanbul', LFHN: 'Europe/Istanbul', SZF: 'Europe/Istanbul',
  LTCS: 'Europe/Istanbul', GNY: 'Europe/Istanbul', LTCP: 'Europe/Istanbul', SIC: 'Europe/Istanbul', LTAR: 'Europe/Istanbul', VAS: 'Europe/Istanbul',
  LTFC: 'Europe/Istanbul', TEQ: 'Europe/Istanbul', LTCI: 'Europe/Istanbul', VAN: 'Europe/Istanbul',
};

export function getAirportTimezone(code: string | null | undefined): string | null {
  if (!code || typeof code !== 'string') return null;
  return AIRPORT_TIMEZONES[code.trim().toUpperCase()] ?? null;
}
