/**
 * OurAirports `municipality` / yaygın İngilizce şehir adı → Türkçe gösterim (dil tr iken).
 * `city_tr` ve airports.ts AIRPORTS önceliklidir; burası DB’deki İngilizce city için yedek.
 * Eşleşme: trim + küçük harf.
 */
const EN_TO_TR: readonly (readonly [string, string])[] = [
  // Turkey
  ['Istanbul', 'İstanbul'],
  ['Izmir', 'İzmir'],
  ['Ankara', 'Ankara'],
  ['Antalya', 'Antalya'],
  ['Bodrum', 'Bodrum'],
  ['Dalaman', 'Dalaman'],
  ['Trabzon', 'Trabzon'],
  ['Adana', 'Adana'],
  ['Mersin', 'Mersin'],
  ['Gaziantep', 'Gaziantep'],
  ['Kayseri', 'Kayseri'],
  ['Konya', 'Konya'],
  ['Samsun', 'Samsun'],
  ['Malatya', 'Malatya'],
  ['Erzurum', 'Erzurum'],
  ['Diyarbakir', 'Diyarbakır'],
  ['Diyarbakır', 'Diyarbakır'],
  ['Sivas', 'Sivas'],
  ['Van', 'Van'],
  ['Batman', 'Batman'],
  ['Elazig', 'Elazığ'],
  ['Elazığ', 'Elazığ'],
  ['Erzincan', 'Erzincan'],
  ['Kahramanmaras', 'Kahramanmaraş'],
  ['Kahramanmaraş', 'Kahramanmaraş'],
  ['Sanliurfa', 'Şanlıurfa'],
  ['Şanlıurfa', 'Şanlıurfa'],
  ['Hatay', 'Hatay'],
  ['Antakya', 'Hatay'],
  ['Canakkale', 'Çanakkale'],
  ['Çanakkale', 'Çanakkale'],
  ['Afyon', 'Afyonkarahisar'],
  ['Eskisehir', 'Eskişehir'],
  ['Eskişehir', 'Eskişehir'],
  ['Denizli', 'Denizli'],
  ['Mugla', 'Muğla'],
  ['Muğla', 'Muğla'],
  ['Balikesir', 'Balıkesir'],
  ['Balıkesir', 'Balıkesir'],
  ['Manisa', 'Manisa'],
  ['Tekirdag', 'Tekirdağ'],
  ['Tekirdağ', 'Tekirdağ'],
  ['Kocaeli', 'Kocaeli'],
  ['Bursa', 'Bursa'],
  ['Adiyaman', 'Adıyaman'],
  ['Adıyaman', 'Adıyaman'],
  ['Agri', 'Ağrı'],
  ['Ağrı', 'Ağrı'],
  ['Igdir', 'Iğdır'],
  ['Iğdır', 'Iğdır'],
  ['Rize', 'Rize'],
  ['Ordu', 'Ordu'],
  ['Sinop', 'Sinop'],
  ['Amasya', 'Amasya'],
  ['Zonguldak', 'Zonguldak'],
  ['Kutahya', 'Kütahya'],
  ['Kütahya', 'Kütahya'],
  ['Usak', 'Uşak'],
  ['Uşak', 'Uşak'],
  ['Nevsehir', 'Nevşehir'],
  ['Nevşehir', 'Nevşehir'],
  ['Mardin', 'Mardin'],
  ['Mus', 'Muş'],
  ['Muş', 'Muş'],
  ['Kars', 'Kars'],
  ['Cankiri', 'Çankırı'],
  ['Çankırı', 'Çankırı'],
  ['Bolu', 'Bolu'],
  ['Sakarya', 'Sakarya'],
  ['Bingol', 'Bingöl'],
  ['Bingöl', 'Bingöl'],
  ['Giresun', 'Giresun'],
  ['Ordu-Giresun', 'Ordu-Giresun'],
  ['Maldives', 'Maldivler'],
  // Germany / DACH
  ['Dusseldorf', 'Düsseldorf'],
  ['Düsseldorf', 'Düsseldorf'],
  ['Cologne', 'Köln'],
  ['Koeln', 'Köln'],
  ['Köln', 'Köln'],
  ['Munich', 'Münih'],
  ['Munchen', 'Münih'],
  ['Nuremberg', 'Nürnberg'],
  ['Nuernberg', 'Nürnberg'],
  ['Frankfurt', 'Frankfurt'],
  ['Hamburg', 'Hamburg'],
  ['Berlin', 'Berlin'],
  ['Hanover', 'Hannover'],
  ['Hannover', 'Hannover'],
  ['Bremen', 'Bremen'],
  ['Leipzig', 'Leipzig'],
  ['Dresden', 'Dresden'],
  ['Stuttgart', 'Stuttgart'],
  ['Dortmund', 'Dortmund'],
  ['Erfurt', 'Erfurt'],
  ['Mulhouse', 'Mulhouse'],
  // Austria / CH
  ['Vienna', 'Viyana'],
  ['Wien', 'Viyana'],
  ['Zurich', 'Zürih'],
  ['Zürich', 'Zürih'],
  ['Basel', 'Basel'],
  ['Geneva', 'Cenevre'],
  ['Genf', 'Cenevre'],
  // Italy
  ['Rome', 'Roma'],
  ['Milan', 'Milano'],
  ['Milano', 'Milano'],
  ['Venice', 'Venedik'],
  ['Venezia', 'Venedik'],
  ['Naples', 'Napoli'],
  ['Napoli', 'Napoli'],
  ['Turin', 'Torino'],
  ['Torino', 'Torino'],
  ['Bologna', 'Bologna'],
  ['Florence', 'Floransa'],
  ['Firenze', 'Floransa'],
  ['Catania', 'Katanya'],
  ['Palermo', 'Palermo'],
  // Spain
  ['Madrid', 'Madrid'],
  ['Barcelona', 'Barselona'],
  ['Valencia', 'Valensiya'],
  ['Seville', 'Sevilla'],
  ['Sevilla', 'Sevilla'],
  ['Bilbao', 'Bilbao'],
  ['Alicante', 'Alicante'],
  ['Malaga', 'Malaga'],
  ['Málaga', 'Malaga'],
  ['Granada', 'Granada'],
  // France
  ['Paris', 'Paris'],
  ['Lyon', 'Lyon'],
  ['Marseille', 'Marsilya'],
  ['Marignane', 'Marsilya'],
  ['Nice', 'Nice'],
  ['Toulouse', 'Toulouse'],
  ['Strasbourg', 'Strazburg'],
  ['Bordeaux', 'Bordo'],
  // UK / Ireland
  ['London', 'Londra'],
  ['Manchester', 'Manchester'],
  ['Birmingham', 'Birmingham'],
  ['Edinburgh', 'Edinburg'],
  ['Glasgow', 'Glasgow'],
  ['Bristol', 'Bristol'],
  ['Leeds', 'Leeds'],
  ['Liverpool', 'Liverpool'],
  ['Newcastle', 'Newcastle'],
  ['Belfast', 'Belfast'],
  ['Dublin', 'Dublin'],
  // Benelux
  ['Amsterdam', 'Amsterdam'],
  ['Rotterdam', 'Rotterdam'],
  ['Eindhoven', 'Eindhoven'],
  ['The Hague', 'Lahey'],
  ['Brussels', 'Brüksel'],
  ['Bruxelles', 'Brüksel'],
  ['Antwerp', 'Antwerp'],
  ['Charleroi', 'Charleroi'],
  // Iberia
  ['Lisbon', 'Lizbon'],
  ['Lisboa', 'Lizbon'],
  ['Porto', 'Porto'],
  ['Oporto', 'Porto'],
  // Nordics
  ['Copenhagen', 'Kopenhag'],
  ['Kobenhavn', 'Kopenhag'],
  ['Stockholm', 'Stokholm'],
  ['Gothenburg', 'Göteborg'],
  ['Goteborg', 'Göteborg'],
  ['Oslo', 'Oslo'],
  ['Bergen', 'Bergen'],
  ['Helsinki', 'Helsinki'],
  ['Reykjavik', 'Reykjavik'],
  // Central / East EU
  ['Warsaw', 'Varşova'],
  ['Warszawa', 'Varşova'],
  ['Krakow', 'Krakov'],
  ['Kraków', 'Krakov'],
  ['Gdansk', 'Gdansk'],
  ['Wroclaw', 'Wroclaw'],
  ['Poznan', 'Poznan'],
  ['Prague', 'Prag'],
  ['Praha', 'Prag'],
  ['Brno', 'Brno'],
  ['Bratislava', 'Bratislava'],
  ['Budapest', 'Budapeşte'],
  ['Bucharest', 'Bükreş'],
  ['Bucuresti', 'Bükreş'],
  ['Cluj', 'Kaloşvar'],
  ['Sofia', 'Sofya'],
  ['Plovdiv', 'Filibe'],
  ['Sarajevo', 'Saraybosna'],
  ['Tuzla', 'Tuzla'],
  ['Belgrade', 'Belgrad'],
  ['Beograd', 'Belgrad'],
  ['Zagreb', 'Zagreb'],
  ['Split', 'Split'],
  ['Dubrovnik', 'Dubrovnik'],
  ['Ljubljana', 'Ljubljana'],
  ['Skopje', 'Üsküp'],
  ['Prizren', 'Prizren'],
  ['Pristina', 'Priştine'],
  ['Prishtina', 'Priştine'],
  ['Tirana', 'Tiran'],
  ['Chisinau', 'Kişinev'],
  ['Chişinău', 'Kişinev'],
  ['Kishinev', 'Kişinev'],
  // Greece / Cyprus
  ['Athens', 'Atina'],
  ['Athina', 'Atina'],
  ['Thessaloniki', 'Selanik'],
  ['Heraklion', 'Kandiye'],
  ['Iraklion', 'Kandiye'],
  ['Chania', 'Hanya'],
  ['Hania', 'Hanya'],
  ['Rhodes', 'Rodos'],
  ['Rodos', 'Rodos'],
  ['Corfu', 'Korfu'],
  ['Santorini', 'Santorini'],
  ['Mykonos', 'Mikonos'],
  ['Larnaca', 'Larnaka'],
  ['Larnaka', 'Larnaka'],
  ['Paphos', 'Baf'],
  ['Nicosia', 'Lefkoşa'],
  ['Ercan', 'Ercan'],
  // Russia / CIS
  ['Moscow', 'Moskova'],
  ['Moskva', 'Moskova'],
  ['Saint Petersburg', 'Sankt Petersburg'],
  ['St Petersburg', 'Sankt Petersburg'],
  ['St. Petersburg', 'Sankt Petersburg'],
  ['Kazan', 'Kazan'],
  ['Grozny', 'Groznı'],
  ['Mineralnye Vody', 'Mineralnye Vody'],
  ['Kyiv', 'Kiev'],
  ['Kiev', 'Kiev'],
  ['Kharkiv', 'Harkov'],
  ['Odessa', 'Odessa'],
  ['Odesa', 'Odessa'],
  ['Lviv', 'Lviv'],
  ['Minsk', 'Minsk'],
  ['Tashkent', 'Taşkent'],
  ['Samarkand', 'Semerkant'],
  ['Almaty', 'Almatı'],
  ['Astana', 'Astana'],
  ['Nur-Sultan', 'Astana'],
  ['Shymkent', 'Şımkent'],
  ['Aktau', 'Aktav'],
  ['Atyrau', 'Atırau'],
  ['Bishkek', 'Bişkek'],
  ['Osh', 'Oş'],
  ['Baku', 'Bakü'],
  ['Ganja', 'Gence'],
  ['Yerevan', 'Erivan'],
  ['Tbilisi', 'Tiflis'],
  ['Batumi', 'Batum'],
  ['Kutaisi', 'Kutaisi'],
  // Gulf / Middle East
  ['Dubai', 'Dubai'],
  ['Abu Dhabi', 'Abu Dabi'],
  ['Sharjah', 'Şarika'],
  ['Doha', 'Doha'],
  ['Manama', 'Manama'],
  ['Kuwait', 'Kuveyt'],
  ['Kuwait City', 'Kuveyt'],
  ['Muscat', 'Maskat'],
  ['Riyadh', 'Riyad'],
  ['Jeddah', 'Cidde'],
  ['Dammam', 'Demmam'],
  ['Medina', 'Medine'],
  ['Mecca', 'Mekke'],
  ['Bahrain', 'Bahreyn'],
  ['Tel Aviv', 'Tel Aviv'],
  ['Tel-Aviv', 'Tel Aviv'],
  ['Jerusalem', 'Kudüs'],
  ['Beirut', 'Beyrut'],
  ['Amman', 'Amman'],
  ['Baghdad', 'Bağdat'],
  ['Basra', 'Basra'],
  ['Erbil', 'Erbil'],
  ['Tehran', 'Tahran'],
  ['Tabriz', 'Tebriz'],
  ['Isfahan', 'İsfahan'],
  ['Mashhad', 'Meşhed'],
  // Africa
  ['Casablanca', 'Kazablanka'],
  ['Marrakech', 'Marakeş'],
  ['Fez', 'Fes'],
  ['Tangier', 'Tanca'],
  ['Cairo', 'Kahire'],
  ['Alexandria', 'İskenderiye'],
  ['Sharm El-Sheikh', 'Şarm El Şeyh'],
  ['Sharm El Sheikh', 'Şarm El Şeyh'],
  ['Hurghada', 'Hurghada'],
  ['Hurghadah', 'Hurghada'],
  ['Luxor', 'Luksor'],
  ['Aswan', 'Asvan'],
  ['Algiers', 'Cezayir'],
  ['Tunis', 'Tunus'],
  ['Tripoli', 'Trablus'],
  ['Johannesburg', 'Johannesburg'],
  ['Cape Town', 'Kapstadt'],
  ['Nairobi', 'Nairobi'],
  ['Addis Ababa', 'Addis Ababa'],
  // Americas
  ['New York', 'New York'],
  ['New York City', 'New York'],
  ['Chicago', 'Şikago'],
  ['Los Angeles', 'Los Angeles'],
  ['Los Angeles CA', 'Los Angeles'],
  ['San Francisco', 'San Francisco'],
  ['Miami', 'Miami'],
  ['Houston', 'Houston'],
  ['Dallas', 'Dallas'],
  ['Atlanta', 'Atlanta'],
  ['Boston', 'Boston'],
  ['Seattle', 'Seattle'],
  ['Denver', 'Denver'],
  ['Phoenix', 'Phoenix'],
  ['Philadelphia', 'Philadelphia'],
  ['Detroit', 'Detroit'],
  ['Orlando', 'Orlando'],
  ['Las Vegas', 'Las Vegas'],
  ['Minneapolis', 'Minneapolis'],
  ['Charlotte', 'Charlotte'],
  ['Washington', 'Vaşington'],
  ['Washington DC', 'Vaşington'],
  ['Washington D.C.', 'Vaşington'],
  ['Newark', 'Newark'],
  ['San Diego', 'San Diego'],
  ['Tampa', 'Tampa'],
  ['St Louis', 'St. Louis'],
  ['St. Louis', 'St. Louis'],
  ['Toronto', 'Toronto'],
  ['Montreal', 'Montreal'],
  ['Montréal', 'Montreal'],
  ['Vancouver', 'Vancouver'],
  ['Calgary', 'Calgary'],
  ['Ottawa', 'Ottawa'],
  ['Edmonton', 'Edmonton'],
  ['Quebec', 'Quebec'],
  ['Mexico City', 'Mexico City'],
  ['Cancun', 'Cancun'],
  ['Bogota', 'Bogota'],
  ['Lima', 'Lima'],
  ['Buenos Aires', 'Buenos Aires'],
  ['Sao Paulo', 'São Paulo'],
  ['São Paulo', 'São Paulo'],
  ['Rio de Janeiro', 'Rio de Janeiro'],
  ['Santiago', 'Santiago'],
  // Asia / Pacific
  ['Hong Kong', 'Hong Kong'],
  ['Singapore', 'Singapur'],
  ['Bangkok', 'Bangkok'],
  ['Phuket', 'Phuket'],
  ['Krabi', 'Krabi'],
  ['Chiang Mai', 'Chiang Mai'],
  ['Kuala Lumpur', 'Kuala Lumpur'],
  ['Jakarta', 'Cakarta'],
  ['Bali', 'Bali'],
  ['Denpasar', 'Denpasar'],
  ['Manila', 'Manila'],
  ['Cebu', 'Cebu'],
  ['Tokyo', 'Tokyo'],
  ['Osaka', 'Osaka'],
  ['Nagoya', 'Nagoya'],
  ['Fukuoka', 'Fukuoka'],
  ['Sapporo', 'Sapporo'],
  ['Seoul', 'Seul'],
  ['Busan', 'Busan'],
  ['Shanghai', 'Şangay'],
  ['Beijing', 'Pekin'],
  ['Guangzhou', 'Guangzhou'],
  ['Shenzhen', 'Shenzhen'],
  ['Chengdu', 'Çengdu'],
  ["Xi'an", 'Sian'],
  ['Xian', 'Sian'],
  ['Urumqi', 'Urumçi'],
  ['Taipei', 'Taipei'],
  ['Kaohsiung', 'Kaohsiung'],
  ['Hanoi', 'Hanoi'],
  ['Ho Chi Minh', 'Ho Chi Minh'],
  ['Ho Chi Minh City', 'Ho Chi Minh'],
  ['Saigon', 'Ho Chi Minh'],
  ['Delhi', 'Delhi'],
  ['New Delhi', 'Yeni Delhi'],
  ['Mumbai', 'Mumbai'],
  ['Bombay', 'Bombay'],
  ['Bengaluru', 'Bengaluru'],
  ['Bangalore', 'Bengaluru'],
  ['Chennai', 'Chennai'],
  ['Kolkata', 'Kalküta'],
  ['Hyderabad', 'Haydarabad'],
  ['Goa', 'Goa'],
  ['Colombo', 'Kolombo'],
  ['Karachi', 'Karaçi'],
  ['Lahore', 'Lahor'],
  ['Islamabad', 'İslamabad'],
  ['Multan', 'Multan'],
  ['Perth', 'Perth'],
  ['Sydney', 'Sidney'],
  ['Melbourne', 'Melbourne'],
  ['Melbourne VIC', 'Melbourne'],
  ['Brisbane', 'Brisbane'],
  ['Auckland', 'Auckland'],
  ['Wellington', 'Wellington'],
  ['Christchurch', 'Christchurch'],
];

const lookup = new Map<string, string>();
for (const [en, tr] of EN_TO_TR) {
  lookup.set(en.trim().toLocaleLowerCase('tr-TR'), tr);
}

function normCityKey(s: string): string {
  return s.trim().toLocaleLowerCase('tr-TR');
}

/** İngilizce / ASCII şehir adını Türkçe karşılığına çevirir; yoksa undefined. */
export function resolveCityNameTr(city: string | null | undefined): string | undefined {
  if (!city || typeof city !== 'string') return undefined;
  const key = normCityKey(city);
  if (!key) return undefined;
  const direct = lookup.get(key);
  if (direct) return direct;
  const paren = key.indexOf('(');
  if (paren > 0) {
    const inner = normCityKey(key.slice(0, paren));
    if (inner) {
      const sub = lookup.get(inner);
      if (sub) return sub;
    }
  }
  return undefined;
}
