/**
 * IATA/ICAO → IANA timezone (THY GMT parser + roster local date).
 * Kaynak: `mobile/constants/airports.ts` AIRPORT_TIMEZONES + `docs/airport-codes.csv` sync.
 */
const IATA_ICAO_TO_IANA: Record<string, string> = {
  LTFJ: 'Europe/Istanbul', SAW: 'Europe/Istanbul', LTFM: 'Europe/Istanbul', IST: 'Europe/Istanbul',
  LTAI: 'Europe/Istanbul', AYT: 'Europe/Istanbul', LTBJ: 'Europe/Istanbul', BJV: 'Europe/Istanbul',
  LTBS: 'Europe/Istanbul', DLM: 'Europe/Istanbul', LTFB: 'Europe/Istanbul', ESB: 'Europe/Istanbul',
  LTCI: 'Europe/Istanbul', LTAF: 'Europe/Istanbul', ADB: 'Europe/Istanbul', IZM: 'Europe/Istanbul',
  LTCG: 'Europe/Istanbul', TZX: 'Europe/Istanbul', LTAH: 'Europe/Istanbul', ADA: 'Europe/Istanbul',
  LTDA: 'Europe/Istanbul', HTY: 'Europe/Istanbul', LTFE: 'Europe/Istanbul', LTAC: 'Europe/Istanbul',
  ANK: 'Europe/Istanbul', LTGP: 'Europe/Istanbul', GZP: 'Europe/Istanbul', LTAP: 'Europe/Istanbul',
  MZH: 'Europe/Istanbul', LTCJ: 'Europe/Istanbul', BAL: 'Europe/Istanbul', LTCU: 'Europe/Istanbul',
  BGG: 'Europe/Istanbul', LTFD: 'Europe/Istanbul', EDO: 'Europe/Istanbul', LTAY: 'Europe/Istanbul',
  DNZ: 'Europe/Istanbul', LTCC: 'Europe/Istanbul', DIY: 'Europe/Istanbul', LTCA: 'Europe/Istanbul',
  EZS: 'Europe/Istanbul', LTCD: 'Europe/Istanbul', ERC: 'Europe/Istanbul', LTCE: 'Europe/Istanbul',
  ERZ: 'Europe/Istanbul', LTAJ: 'Europe/Istanbul', GZT: 'Europe/Istanbul', LTCT: 'Europe/Istanbul',
  IGD: 'Europe/Istanbul', LTCN: 'Europe/Istanbul', KCM: 'Europe/Istanbul', LTCF: 'Europe/Istanbul',
  KSY: 'Europe/Istanbul', LTAU: 'Europe/Istanbul', ASR: 'Europe/Istanbul', LTAN: 'Europe/Istanbul',
  KYA: 'Europe/Istanbul', LTBZ: 'Europe/Istanbul', KZR: 'Europe/Istanbul', LTAT: 'Europe/Istanbul',
  MLX: 'Europe/Istanbul', LTCR: 'Europe/Istanbul', MQM: 'Europe/Istanbul', LTCK: 'Europe/Istanbul',
  MSR: 'Europe/Istanbul', LTCB: 'Europe/Istanbul', OGU: 'Europe/Istanbul', OGZ: 'Europe/Istanbul',
  LTFU: 'Europe/Istanbul', ISE: 'Europe/Istanbul', LTFV: 'Europe/Istanbul', RZV: 'Europe/Istanbul',
  LTFH: 'Europe/Istanbul', SZF: 'Europe/Istanbul', LTCS: 'Europe/Istanbul', GNY: 'Europe/Istanbul',
  LTCP: 'Europe/Istanbul', ADF: 'Europe/Istanbul', LTCQ: 'Europe/Istanbul', NOP: 'Europe/Istanbul',
  SIC: 'Europe/Istanbul', LTAR: 'Europe/Istanbul', VAS: 'Europe/Istanbul', LTFC: 'Europe/Istanbul',
  TEQ: 'Europe/Istanbul', VAN: 'Europe/Istanbul', LTBY: 'Europe/Istanbul', AFY: 'Europe/Istanbul',
  LTCO: 'Europe/Istanbul', AJI: 'Europe/Istanbul', AOE: 'Europe/Istanbul', LTBH: 'Europe/Istanbul',
  CKZ: 'Europe/Istanbul', LTAL: 'Europe/Istanbul', KFS: 'Europe/Istanbul', LTBQ: 'Europe/Istanbul',
  KCO: 'Europe/Istanbul', ECN: 'Asia/Nicosia', LCEN: 'Asia/Nicosia',
  OPKC: 'Asia/Karachi', KHI: 'Asia/Karachi', OPRN: 'Asia/Karachi', ISB: 'Asia/Karachi',
  OPLA: 'Asia/Karachi', LHE: 'Asia/Karachi',
  EDDF: 'Europe/Berlin', FRA: 'Europe/Berlin', EDDM: 'Europe/Berlin', MUC: 'Europe/Berlin',
  EDDL: 'Europe/Berlin', DUS: 'Europe/Berlin', EDDB: 'Europe/Berlin', BER: 'Europe/Berlin',
  EGLL: 'Europe/London', LHR: 'Europe/London', EGKK: 'Europe/London', LGW: 'Europe/London',
  EHAM: 'Europe/Amsterdam', AMS: 'Europe/Amsterdam', LFPG: 'Europe/Paris', CDG: 'Europe/Paris',
  LEMD: 'Europe/Madrid', MAD: 'Europe/Madrid', LEBL: 'Europe/Madrid', BCN: 'Europe/Madrid',
  LOWW: 'Europe/Vienna', VIE: 'Europe/Vienna', LSZH: 'Europe/Zurich', ZRH: 'Europe/Zurich',
  OMDB: 'Asia/Dubai', DXB: 'Asia/Dubai', OMAA: 'Asia/Dubai', AUH: 'Asia/Dubai',
  OTBD: 'Asia/Qatar', OTHH: 'Asia/Qatar', DOH: 'Asia/Qatar',
  UUEE: 'Europe/Moscow', SVO: 'Europe/Moscow', UUWW: 'Europe/Moscow', VKO: 'Europe/Moscow',
  UUDD: 'Europe/Moscow', DME: 'Europe/Moscow', ULLI: 'Europe/Moscow', LED: 'Europe/Moscow',
  DTTA: 'Africa/Tunis', TUN: 'Africa/Tunis', UTSA: 'Asia/Samarkand', NAV: 'Asia/Samarkand',
  LCLK: 'Asia/Nicosia', LCA: 'Asia/Nicosia', LCRA: 'Asia/Nicosia', PFO: 'Asia/Nicosia',
  OBBI: 'Asia/Bahrain', BAH: 'Asia/Bahrain', OKBK: 'Asia/Kuwait', KWI: 'Asia/Kuwait',
  OOMS: 'Asia/Muscat', MCT: 'Asia/Muscat', OERK: 'Asia/Riyadh', RUH: 'Asia/Riyadh',
  OEJN: 'Asia/Riyadh', JED: 'Asia/Riyadh', OEDR: 'Asia/Riyadh', DMM: 'Asia/Riyadh',
  OIIE: 'Asia/Tehran', IKA: 'Asia/Tehran', LGAV: 'Europe/Athens', ATH: 'Europe/Athens',
  LIRF: 'Europe/Rome', FCO: 'Europe/Rome', LIML: 'Europe/Rome', MXP: 'Europe/Rome',
  LPPT: 'Europe/Lisbon', LIS: 'Europe/Lisbon', EBBR: 'Europe/Brussels', BRU: 'Europe/Brussels',
  KJFK: 'America/New_York', JFK: 'America/New_York', KEWR: 'America/New_York', EWR: 'America/New_York',
  KIAD: 'America/New_York', IAD: 'America/New_York', KORD: 'America/Chicago', ORD: 'America/Chicago',
  KLAX: 'America/Los_Angeles', LAX: 'America/Los_Angeles', KSFO: 'America/Los_Angeles', SFO: 'America/Los_Angeles',
  CYYZ: 'America/Toronto', YYZ: 'America/Toronto', VHHH: 'Asia/Hong_Kong', HKG: 'Asia/Hong_Kong',
  WSSS: 'Asia/Singapore', SIN: 'Asia/Singapore', VTBS: 'Asia/Bangkok', BKK: 'Asia/Bangkok',
  RJAA: 'Asia/Tokyo', NRT: 'Asia/Tokyo', RJTT: 'Asia/Tokyo', HND: 'Asia/Tokyo',
  ZSPD: 'Asia/Shanghai', PVG: 'Asia/Shanghai', VIDP: 'Asia/Kolkata', DEL: 'Asia/Kolkata',
  VABB: 'Asia/Kolkata', BOM: 'Asia/Kolkata', HEBA: 'Africa/Cairo', HBE: 'Africa/Cairo',
  HEGN: 'Africa/Cairo', HRG: 'Africa/Cairo', HESH: 'Africa/Cairo', SSH: 'Africa/Cairo',
  GMMN: 'Africa/Casablanca', CMN: 'Africa/Casablanca', OJAM: 'Asia/Amman', AMM: 'Asia/Amman',
  OLBA: 'Asia/Beirut', BEY: 'Asia/Beirut', OEMA: 'Asia/Riyadh', MED: 'Asia/Riyadh',
  EPWA: 'Europe/Warsaw', WAW: 'Europe/Warsaw', LROP: 'Europe/Bucharest', OTP: 'Europe/Bucharest',
  LYBE: 'Europe/Belgrade', BEG: 'Europe/Belgrade', ESSA: 'Europe/Stockholm', ARN: 'Europe/Stockholm',
  EKCH: 'Europe/Copenhagen', CPH: 'Europe/Copenhagen', ENGM: 'Europe/Oslo', OSL: 'Europe/Oslo',
  EIDW: 'Europe/Dublin', DUB: 'Europe/Dublin', LFPO: 'Europe/Paris', ORY: 'Europe/Paris',
  EPKK: 'Europe/Warsaw', KRK: 'Europe/Warsaw', UAAA: 'Asia/Almaty', ALA: 'Asia/Almaty',
  UACC: 'Asia/Almaty', NQZ: 'Asia/Almaty', UAFM: 'Asia/Bishkek', FRU: 'Asia/Bishkek',
  UGSB: 'Asia/Tbilisi', BUS: 'Asia/Tbilisi', UGTB: 'Asia/Tbilisi', TBS: 'Asia/Tbilisi',
  ORBI: 'Asia/Baghdad', BGW: 'Asia/Baghdad', LLBG: 'Asia/Jerusalem', TLV: 'Asia/Jerusalem',
  LTAI: 'Europe/Istanbul', AYT: 'Europe/Istanbul',
};

export function getAirportIanaTimezone(code: string | null | undefined): string | undefined {
  if (!code) return undefined;
  const key = code.trim().toUpperCase();
  return IATA_ICAO_TO_IANA[key];
}
