create table if not exists public.fr24_usage_metric_snapshots (
  id bigint generated by default as identity primary key,
  fetched_at timestamptz not null default now(),
  period text not null default '30d',
  source_url text not null,
  total_calls bigint,
  total_credits numeric,
  endpoint_count integer not null default 0,
  raw jsonb not null
);

create index if not exists fr24_usage_metric_snapshots_fetched_at_idx
  on public.fr24_usage_metric_snapshots (fetched_at desc);

create table if not exists public.fr24_usage_metric_points (
  id bigint generated by default as identity primary key,
  snapshot_id bigint not null references public.fr24_usage_metric_snapshots(id) on delete cascade,
  endpoint text not null,
  metric_date date,
  calls bigint,
  credits numeric,
  raw jsonb
);

create index if not exists fr24_usage_metric_points_snapshot_idx
  on public.fr24_usage_metric_points (snapshot_id);

create index if not exists fr24_usage_metric_points_date_idx
  on public.fr24_usage_metric_points (metric_date desc);

create index if not exists fr24_usage_metric_points_endpoint_idx
  on public.fr24_usage_metric_points (endpoint);

alter table public.fr24_usage_metric_snapshots enable row level security;
alter table public.fr24_usage_metric_points enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'fr24_usage_metric_snapshots'
      and policyname = 'fr24 usage snapshots readable by authenticated'
  ) then
    create policy "fr24 usage snapshots readable by authenticated"
      on public.fr24_usage_metric_snapshots
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'fr24_usage_metric_points'
      and policyname = 'fr24 usage points readable by authenticated'
  ) then
    create policy "fr24 usage points readable by authenticated"
      on public.fr24_usage_metric_points
      for select
      to authenticated
      using (true);
  end if;
end$$;

comment on table public.fr24_usage_metric_snapshots is
  'Periodic raw snapshots fetched from FR24 usage metrics endpoint.';
comment on table public.fr24_usage_metric_points is
  'Normalized endpoint/day points parsed from FR24 usage metrics snapshots.';
